### ISSUE TITLE
The extension breaks the HTML5 player.

### ISSUE THREAD

**Issue by Daniil1288** [vixing/tbf-extension#4]
Following the steps provided here: https://www.reddit.com/r/Twitch/comments/4q5mci/are_we_ever_getting_html5/d4qeljf
results in a black screen. After disabling the extension everything is back to normal.

After Twitch implements the HTML5 player fully and decides to finally use it instead of Flash, the extension will most likely break.

Also, someone published your extension (probably without your permission) on Chrome's extension store here: https://chrome.google.com/webstore/detail/twitch-buffering-fix/gkjmnenojhaiobfffgjllajkahggbikf

**Comment by vixing** [comment]
Thank you for the information. I didn't know someone did that :o
You can get my extension from
http://www.crx4chrome.com/extensions/nnahmgokconolakhpdmgnmgaokhjcncb/ and
it's not breaking the player.
Simply download the crx and drag it on Extensions tab to install it. It's
safe and works.

Thanks again!

2016-06-28 19:33 GMT+02:00 Daniil1288 <notifications@github.com>:

**Comment by Daniil1288** [comment]
> Thanks again!

no problem, glad to be of service :)
